'------------------------------------------------------------------------------
' <auto-generated>
'    このコードはテンプレートから生成されました。
'
'    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class BerthPlanEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BerthPlanEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property mBerth() As DbSet(Of mBerth)
    Public Property mCompany() As DbSet(Of mCompany)
    Public Property mPilot() As DbSet(Of mPilot)
    Public Property mVessel() As DbSet(Of mVessel)
    Public Property mWharf() As DbSet(Of mWharf)
    Public Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Property mMessage() As DbSet(Of mMessage)
    Public Property tSchedule() As DbSet(Of tSchedule)
    Public Property mUser() As DbSet(Of mUser)
    Public Property tBoard() As DbSet(Of tBoard)
    Public Property tBoardFile() As DbSet(Of tBoardFile)
    Public Property tBoardView() As DbSet(Of tBoardView)

End Class
