'------------------------------------------------------------------------------
' <auto-generated>
'    このコードはテンプレートから生成されました。
'
'    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mCompany
    Public Property ID As Integer
    Public Property ApplicantCD As String
    Public Property ApplicantName As String
    Public Property PostCode As String
    Public Property Address As String
    Public Property Tel As String
    Public Property Fax As String
    Public Property Email As String
    Public Property Color As String
    Public Property UpdTime As Date
    Public Property UpdUserID As String
    Public Property UpdPGID As String
    Public Property TimeStamp As Byte()
    Public Property Flag As Boolean

End Class
