'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace BerthPlan

    Partial Public Class mMessage
        Public Property ID As Integer
        Public Property MessageID As String
        Public Property UpdTime As Date
        Public Property UpdUserID As String
        Public Property UpdUPGID As String
        Public Property TimeStamp As Byte()
        Public Property MessageContent As String
    
    End Class

End Namespace
