'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace BerthPlan

    Partial Public Class mUser
        Public Property ID As Integer
        Public Property UserID As String
        Public Property UserName As String
        Public Property Password As String
        Public Property EmailAddress As String
        Public Property ApplicantCD As String
        Public Property UpdTime As Date
        Public Property UpdUserID As String
        Public Property UpdPGID As String
        Public Property TimeStamp As Byte()
        Public Property LastLogin As Nullable(Of Date)
        Public Property IsAdmin As Boolean
        Public Property Flag As Boolean
    
    End Class

End Namespace
