'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class mVessel
    Public Property ID As Integer
    Public Property VesselCD As String
    Public Property VesselName As String
    Public Property IMO As String
    Public Property ApplicantCD As String
    Public Property GrossTon As Decimal
    Public Property Nationality As String
    Public Property LOA As Decimal
    Public Property IO As Boolean
    Public Property UpdTime As Date
    Public Property UpdUserID As String
    Public Property UpdPGID As String
    Public Property TimeStamp As Byte()
    Public Property Flag As Boolean

End Class
