'------------------------------------------------------------------------------
' <auto-generated>
'    このコードはテンプレートから生成されました。
'
'    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class sysdiagrams
    Public Property name As String
    Public Property principal_id As Integer
    Public Property diagram_id As Integer
    Public Property version As Nullable(Of Integer)
    Public Property definition As Byte()

End Class
