'------------------------------------------------------------------------------
' <auto-generated>
'    このコードはテンプレートから生成されました。
'
'    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tBoardView
    Public Property BoardViewID As Integer
    Public Property UserID As Integer
    Public Property BoardID As Integer
    Public Property IsChecked As Boolean
    Public Property UpdTime As Date
    Public Property UpdUserID As String
    Public Property UpdPGID As String
    Public Property TimeStamp As Byte()
    Public Property Flag As Boolean

End Class
