'------------------------------------------------------------------------------
' <auto-generated>
'    このコードはテンプレートから生成されました。
'
'    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tBoard
    Public Property BoardID As Integer
    Public Property Title As String
    Public Property Contents As String
    Public Property PostingStartDate As Date
    Public Property PostingEndDate As Date
    Public Property HyperLink As String
    Public Property CreateUserID As String
    Public Property CreatedTime As Date
    Public Property UpdTime As Date
    Public Property UpdUserID As String
    Public Property UpdPGID As String
    Public Property TimeStamp As Byte()
    Public Property Flag As Boolean

End Class
