'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tBoardCompany
    Public Property ID As Integer
    Public Property BoardID As Integer
    Public Property CompanyID As Integer
    Public Property ApplicantCD As String
    Public Property ApplicantName As String
    Public Property UpdTime As Date
    Public Property UpdUserID As String
    Public Property UpdPGID As String
    Public Property TimeStamp As Date
    Public Property Flag As Boolean

End Class
