'------------------------------------------------------------------------------
' <auto-generated>
'    このコードはテンプレートから生成されました。
'
'    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tSchedule
    Public Property ScheduleID As Integer
    Public Property VesselCD As String
    Public Property VoyageNo As String
    Public Property BerthID As Integer
    Public Property ApplicantCD As String
    Public Property PilotCD As String
    Public Property PilotGuide As Boolean
    Public Property Tag As Boolean
    Public Property LineBoat As Boolean
    Public Property ETA As Date
    Public Property ETB As Date
    Public Property ETD As Date
    Public Property ShipFace As Boolean
    Public Property UpdTime As Date
    Public Property UpdUserID As String
    Public Property UpdPGID As String
    Public Property TimeStamp As Byte()
    Public Property Flag As Boolean

End Class
