'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace BerthPlan

    Partial Public Class tSchedule
        Public Property ScheduleID As Integer
        Public Property VesselCD As String
        Public Property VoyageNo As String
        Public Property BerthID As Integer
        Public Property ApplicantCD As String
        Public Property PilotCD As String
        Public Property PilotGuide As Boolean
        Public Property Tag As Boolean
        Public Property LineBoat As Boolean
        Public Property ETA As Date
        Public Property ETB As Date
        Public Property ETD As Date
        Public Property ShipFace As Boolean
        Public Property UpdTime As Date
        Public Property UpdUserID As String
        Public Property UpdPGID As String
        Public Property TimeStamp As Byte()
        Public Property Flag As Boolean
    
    End Class

End Namespace
